// <auto-generated />
using System;
using EfcData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfcData.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Assigntment1.models.SubForum", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnedByPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("OwnedByPassword");

                    b.ToTable("SubForums");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Password");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Assigntment1.models.SubForum", b =>
                {
                    b.HasOne("Entities.Models.User", "OwnedBy")
                        .WithMany()
                        .HasForeignKey("OwnedByPassword");

                    b.Navigation("OwnedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
